file:
  upload-dir: /Users/apple/gis/uploads
logging:
  level:
    root: info
server:
  port: 8318
spring:
  datasource:
    password: root
    url: jdbc:mysql://localhost:3306/gis?charset=utf8&useSSl=true&autoReconnect=true&characterEncoding=utf8
    username: root
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 200MB
      max-request-size: 200MB
